import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ClientWrapper from './components/layout/wrapper/client-wrapper';

const yekan = localFont({
  src: [
    { path: './fonts/Yekan.woff2' },
    { path: './fonts/Yekan.woff' },
    { path: './fonts/Yekan.eot' },
    { path: './fonts/Yekan.ttf' },
  ],
  variable: '--font-yekan',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Boolooz',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${yekan.variable}  antialiased`}>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
